### ISSUE TITLE
Create a sitemap.xml file for beta.get.gov

### ISSUE THREAD

**Issue by michelle-rago** [cisagov/get.gov#124]
# 💡 Summary #

Create a sitemap.xml file for beta.get.gov to support indexing by search.gov. 

Blocks #126 

## Implementation notes ##

- Search.gov said "Could you please update https://beta.get.gov/sitemap.xml with fully qualified urls, instead of just paths?"
- There is this file, https://github.com/cisagov/getgov-home/blob/beta/sitemap.xml.njk, but I'm not sure what it's doing.
- [Search.gov info on sitemaps](https://search.gov/indexing/sitemaps.html)

## Acceptance criteria ##

How do we know when this work is done?

- [ ] We have a sitemap.xml file that search.gov can use to index beta.get.gov.

**Comment by vickyszuchin** [comment]
Per Neil, 11/29), this is a static site that is built with 11ty, a static site generator. The sitemap is static and ideally it could be built at the same time as the site using an 11ty plugin.
