### ISSUE TITLE
Develop content and workflow for "featured .gov" feature

### ISSUE THREAD

**Issue by michelle-rago** [cisagov/get.gov#127]
We'd like to feature various .gov sites to give inspiration for other government agencies and to showcase the great work across .gov domains. 

## Acceptance criteria

- [x] Create list of diverse .gov domains we can feature (at least 30 to start with)
- [x] Create a plan for updating the homepage with these domains
- [x] Decide how we'll actually add or update content
- [x] Write a one-line description about each domain
- [ ] ~Collect individual favicons for each featured domain~
- [ ] Plan to reach out to those we decide to reach out to
- [ ] Preliminary plan for metrics (click-thru rate, for example)
- [ ] Create an implementation issue for engineering (if necessary) or create an issue to automate delivery of this feature in the future
- [ ] (Kristina) Create a guide on how to make monthly updates

## Additional context
* @amcelya's [draft](https://docs.google.com/document/d/1jkiWrB1YCdhTD85xWDzJhg3gb0Sk_HnXYg-2SjGeDko/edit?usp=sharing)

## Note
USWDS summary box heading seems off ("Featured .gov" heading does not seem to be the same size as "The latest from .gov" heading to the left).

**Comment by h-m-f-t** [comment]
@amcelya has prepared a document, should sync it with @Katherine-Osos.

**Comment by h-m-f-t** [comment]
@amcelya @kristinacyin what's left here?
