### ISSUE TITLE
Add blog subscription functionality

### ISSUE THREAD

**Issue by michelle-rago** [cisagov/get.gov#128]
- [ ] Confirm if we require the subscription feature
- [ ] If it is required capture implementation AC
- [ ] If not required add AC to remove the subscription button from the page.

**Comment by PaulKuykendall** [comment]
Prod/design revisited this on Tuesday Dec 05, confirmed that Cameron, on prev Friday with Paul, agreed to deprioritize this.

**Comment by vickyszuchin** [comment]
"Refinement" tag added: ACs need to be further defined.

**Comment by katypies** [comment]
Closing this. We should have subscription functionality in the future, but we're not publishing often enough right now for it to make a ton of sense.
