### ISSUE TITLE
Form submission for domain search doesn't handle Enter keypress

### ISSUE THREAD

**Issue by aduth** [cisagov/get.gov#145]
# 🐛 Summary #

When pressing the <kbd>Enter</kbd> key to submit a domain search on https://beta.get.gov/ ([implicit submission](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission)), the page reloads and does not display any search results. This is different from clicking the "Check availability" button, which displays an inline search result after checking availability.

## To reproduce ##

1. Go to https://beta.get.gov/
2. Under "Start your .gov domain search", enter "example" in the text field
3. Press <kbd>Enter</kbd> on your keyboard

## Expected behavior ##

The results of the search ("example.gov isn't available" in this example) are shown.

Instead, the page reloads with no results shown.

## Notes ##

The problem may lie in the button being `type="button"` with an `onclick` handler:

https://github.com/cisagov/getgov-home/blob/971bcf844f7fd9b7a17a5da4d9f42954137e74b1/_includes/domain-search.html#L95-L96

Instead, if the button were `type="submit"`, and the event handler being attached to the form's `onsubmit` handler (with `event.preventDefault` called on the submission event), it would work as expected.

**Comment by h-m-f-t** [comment]
Hi @aduth, thanks for the issue! We've got a PR to address this (https://github.com/cisagov/getgov-home/pull/122) in a slightly different way than you've proposed, but we'll take a look at your comments and leave the issue open until it's resolved.

**Comment by h-m-f-t** [comment]
Fixed in #122. Thanks again for the issue @aduth!
