### ISSUE TITLE
Inform users of .gov requirements before starting a new domain request

### ISSUE THREAD

**Issue by michelle-rago** [cisagov/get.gov#147]
### Issue description

This ticket is for implementing the designs for https://github.com/cisagov/manage.get.gov/issues/547, also known as the preamble and only for the beta.get.gov portion

Flow from **_beta.get.gov_**:
- When user clicks a button or link to start a new request, a modal appears displaying the Login requirements. 
- Upon logging in (now on manage.get.gov) user is immediately taken to the request flow (rather than the dashboard)

in the related ticket ([#1485](https://github.com/cisagov/manage.get.gov/issues/1485)) on manage.get.gov, a page will need to be added on the application when a user clicks these links/buttons. This needs to be considered during implementation
### Acceptance criteria

- [x] Users clicking the button/links to **start a domain request** from beta.get.gov are shown info about requirements to complete the form, including Login.gov requirements (see the text in additional context)
- [x] after clicking the button/links mentioned and the user moves past the modal + logs in, then they are redirected to a new application 
- [ ] ground work is set for #[1485](https://github.com/cisagov/manage.get.gov/issues/1485) so that when this button/link is clicked a page can be shown conditionally.
- [ ] Don't merge until we are ready to launch

### Additional context

- [New text for both flows](https://docs.google.com/document/d/15FpRLKXGeeNJ5D8uCu1YtRDZSWN5ZrJPKXJV4tCY6fw/edit#heading=h.cldogb82du8p)
- [Mural with flows](https://app.mural.co/t/gsa6/m/gsa6/1701893071504/3b10ecf79684c8e3a1387d7fe5665b58f3c156fa?sender=michellerago0372)
- Figma mockup: [Flow from beta.get.gov](https://www.figma.com/proto/aJbuDLJNNikqQObTuCNKQa/GetGov_Designs_ECS-Truss?page-id=2913%3A27400&type=design&node-id=2927-42517&viewport=131%2C74%2C0.14&t=l70YtUOmnoE59X5H-1&scaling=min-zoom&starting-point-node-id=2927%3A42517&show-proto-sidebar=1&mode=design) and [flow from manage.get.gov](https://www.figma.com/proto/aJbuDLJNNikqQObTuCNKQa/GetGov_Designs_ECS-Truss?page-id=2913%3A27400&type=design&node-id=2926-28192&viewport=131%2C74%2C0.14&t=VIQ4EPkC3bwHn9Xk-1&scaling=min-zoom&starting-point-node-id=2926%3A28192&show-proto-sidebar=1&mode=design)

Note: Some of the text in the document above includes  text for a new page is inserted before the "org type" step of the request flow that will be added in the related ticket. See the whole overall flow in the mural. 

Don't merge until the launch date as this allows a new domain request to be started, we don't want that until we are ready. 

If you need help finding all buttons/links, reach out to a designer for assistance.

### Links to other issues

Design ticket: https://github.com/cisagov/manage.get.gov/issues/547
Related to: cisagov/manage.get.gov#1485

**Comment by PaulKuykendall** [comment]
@gabydisarli - Please update the Figma to insert the "You're about the start a .gov domain request" page

**Comment by gabydisarli** [comment]
> @gabydisarli - Please update the Figma to insert the "You're about the start a .gov domain request" page

done!
