### ISSUE TITLE
Add ability to have subnav on get.gov pages

### ISSUE THREAD

**Issue by michelle-rago** [cisagov/get.gov#170]
We'd like to add subnav on get.gov pages. For example, the software engineering links in this screenshot would be indented under the Jobs section. 

![Image](https://github.com/cisagov/getgov-home/assets/60157596/3fc37951-4506-42a5-920e-2c5874e13fa9)

An 11ty site example with subnav
- The [subnav on these pages](https://guides.18f.gov/engineering/our-approach/architecture-reviews/) are all anchor links.  We want to add subnav that will link to new pages (not anchor links). 

A/C

- [ ] https://get.gov/about/jobs/ will only show two engineering positions when on https://get.gov/about/jobs/ but not on https://get.gov/about/

Additional Context:
- Refer to DNS Child pages for example of how this has been implemented already.
- We'll use this work as an example for future design work that requires a subnav

**Comment by vickyszuchin** [comment]
Per Michelle,

We'll need it for the https://beta.get.gov/domains/requirements/ page and most likely other pages in the future. I could see us using it for help content too. The solution for one page will be the same used for all pages on the beta site.
