### ISSUE TITLE
404 errors aren't formatted correctly

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/get.gov#205]
### Current Behavior

Navigating to beta.get.gov/register and beta.get.gov/request result in improperly formatted 404 error. 

![image](https://github.com/cisagov/manage.get.gov/assets/144387994/04cffaef-eaf1-4341-9431-6eeca154cb21)

### Expected Behavior

Navigating to endpoint that is not part of the beta.get.gov url results in normal 404 page. 

### Steps to Reproduce

1. Navigate to beta.get.gov/register
2. Navigate to beta.get.gov/request
3. See error message

### Environment

Prof

### Additional Context

Identified in pre-launch testing. See [issues](https://docs.google.com/document/d/1GvNzvdFOHL8jIiuDfmcxAFXeXXpbkoQx4XkRtAfSVOw/edit)

This is likely a cloud.gov Pages issue, a product of us change this repo's name. See https://cloud.gov/pages/documentation/customization/#custom-domain-404-page

**Comment by h-m-f-t** [comment]
I've reached out to Pages to ask if they can update our 404 location.

**Comment by abroddrick** [comment]
![Image](https://github.com/cisagov/get.gov/assets/109625347/506f51f4-4241-4a4d-8b3e-61c2bab2cfa9)

closing this as the issue appears resolved.
