### ISSUE TITLE
Get.gov sitemap is showing errors on Google Search Console

### ISSUE THREAD

**Issue by michelle-rago** [cisagov/get.gov#224]
### Current Behavior

The https://get.gov/sitemap.xml is not showing the full URLs. 

Google highlighted the errors:
![image](https://github.com/cisagov/get.gov/assets/60157596/ed7044b2-6633-42e1-af69-9108cfe05503)

### Expected Behavior

Full URLs should appear in the sitemap, including the https. The sitemap was working when the site was in beta.

### Steps to Reproduce

Go to https://get.gov/sitemap.xml

**Comment by vickyszuchin** [comment]
[Slack thread](https://cisa-corp.slack.com/archives/C03QM0JGSQG/p1706733378255069) that initiated the creation of this ticket.

**Comment by vickyszuchin** [comment]
Marked this ticket as Done per [slack thread](https://cisa-corp.slack.com/archives/C05BGB4L5NF/p1707335207702349). 

cc: @michelle-rago
