### ISSUE TITLE
Linkify H2-H6 anchors to make sharing URLs more useful

### ISSUE THREAD

**Issue by h-m-f-t** [cisagov/get.gov#255]
### Issue description

When helping users, the program team often shares a URL directly to the page _and content on the page_ (e.g., https://get.gov/domains/before/#steps-to-take-before-you-request-your-.gov-domain). We craft the URL manually by going to browser dev tools and grabbing the ID to append to the URL. Users who click the link land directly on the page _and_ at the content we want them to see on the page.

To streamline this and make our content easier to direct-link to, let's make headers linkable.

### Acceptance criteria

- [x] headers' styling should change (on mouseover but without an icon). 
  * As an example, see [how GitHub docs behave](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)
- [x] Headers (2-6) should be linkified, allowing anyone to click a header and have their browser directed to that content
- [x] Ensure special characters are stripped in this link
- [x] The above should apply to current headers and future headers

### Additional context

* Cameron doesn't have a strong preference on the styling question
* We should take care to follow any USWDS guidance on this, particularly around [accessibility](https://designsystem.digital.gov/components/in-page-navigation/#accessibility-guidance:~:text=Set%20focus%20state%20on%20section%20target%20for%20keyboard%20users.)

**Comment by abroddrick** [comment]
@Katherine-Osos does design want to weigh in on AC #1 or is this intended to just be an engineering only determination?

**Comment by Katherine-Osos** [comment]
I think underlining the heading upon mouseover makes sense. But I don't think a link icon is necessary (as in the GitHub example) @gabydisarli Any opinion on how this should look?

**Comment by gabydisarli** [comment]
> I think underlining the heading upon mouseover makes sense. But I don't think a link icon is necessary (as in the GitHub example) @gabydisarli Any opinion on how this should look?

Agreed! I love the underline on mouseover, but would pass on the always present icon

**Comment by vickyszuchin** [comment]
Per guidance, any "In review" tickets from sprint 45 will be moved over to Sprint 46 noon EST on Day 4 (5/28).
