### ISSUE TITLE
Capture clicks on internal search results

### ISSUE THREAD

**Issue by michelle-rago** [cisagov/get.gov#259]
### Current Behavior

Our search.gov data is showing queries, but not clicks. We need to add code to track the clicks. 

Instructions are here https://open.gsa.gov/api/searchgov-clicks/ and in search.gov. 

You need to be logged in to see the instructions on search.gov https://search.usa.gov/sites/9335/click_tracking_api_instructions. 

@rachidatecs and @h-m-f-t have access to our search.gov account.

### Expected Behavior

We will see clicks on our internal search results in the search.gov data/dashboard.

### Steps to Reproduce

1. Log in to search.gov.
2. You will not see clicks.

**Comment by kristinacyin** [comment]
Michelle gave me an overview of the issue and I have access to search.gov console now. This might be a good ticket for me to work on
