### ISSUE TITLE
Build out a prototype of an updated Contact Us form

### ISSUE THREAD

**Issue by h-m-f-t** [cisagov/get.gov#289]
### Issue description

In #288, we experimented with modifying the Contact Us form to guide users to the right answers so (perhaps) they don't need to submit the form at all. In this issue, let's build a working prototype of the form and solicit more feedback from the team on whether the approach is viable.

### Acceptance criteria

- [x] Using the [FAQs](https://get.gov/help/faq/) as a guide, build a prototype of a new form using the approach started in the duplicate [contact us](https://forms.office.com/Pages/DesignPageV2.aspx?origin=NeoPortalPage&subpage=design&id=bOfNPG2UEkq7evydCEI1SqHke9Gh6wJEl3kQ5EjWUKlURE04OUo3WTYyUEhIVENXSFlGNU01WjVaNy4u) form (if needed, ask @h-m-f-t to be added as a collaborator on the form).
- [x] Present an MVP for feedback to @cisagov/gov-designers (needn't account for every permutation but should be functional for several common questions)
- [x] As a team, decide go/no go. If go, create an implementation issue

### Additional context

#288 talked about exploring the sending of emails upon submission. We didn't explore that, but that could also be part of the final implementation.

### Links to other issues

🔄 Relates to #288

**Comment by kristinacyin** [comment]
[Prototype form](https://forms.office.com/Pages/ResponsePage.aspx?id=bOfNPG2UEkq7evydCEI1SqHke9Gh6wJEl3kQ5EjWUKlURE04OUo3WTYyUEhIVENXSFlGNU01WjVaNy4u)
[Feedback (Slack thread)](https://cisa-corp.slack.com/archives/C05BDEA3C11/p1716217719659259)
