### ISSUE TITLE
Content: Provide answers in contact form

### ISSUE THREAD

**Issue by kristinacyin** [cisagov/get.gov#300]
### Issue description

In #288, we experimented with modifying the Contact Us form to guide users to the right answers so (perhaps) they don't need to submit the form at all. In #289, we tested out the viability of updating the form with a prototype. Now, we need to finalize the content before implementing changes. 

### Acceptance criteria

- [x] Create a Google doc that includes updated form content and branching logic
- [x] Share Google doc with team for feedback
- [x] Create a ticket to implement changes to the form

### Additional context

Link to [Google doc](https://docs.google.com/document/d/1kmw4HHacwl_sHyPvNmInRrFzguCaT-F60t_qX-ki7kI/edit)
Link to [prototype](https://forms.office.com/Pages/ResponsePage.aspx?id=bOfNPG2UEkq7evydCEI1SqHke9Gh6wJEl3kQ5EjWUKlURE04OUo3WTYyUEhIVENXSFlGNU01WjVaNy4u)

### Links to other issues

Steps for updating the form:

1. #288 
2. #289 
3. #300  (📍 YOU ARE HERE)
4. #303 

Note; This effort will update the Microsoft Form, but will not replace it. We will work on replacing the contact form with our own customized solution in [#2011](https://github.com/cisagov/manage.get.gov/issues/2011) and [#2099](https://github.com/cisagov/manage.get.gov/issues/2099)

**Comment by vickyszuchin** [comment]
Per guideline, all "In review" tickets from Sprint 47 will moved forward at noon EST on Day 4 of new sprint (Sprint 48).
