### ISSUE TITLE
Implement answers to contact form

### ISSUE THREAD

**Issue by kristinacyin** [cisagov/get.gov#303]
### Issue description

In https://github.com/cisagov/get.gov/issues/288, we experimented with modifying the Contact Us form to guide users to the right answers so (perhaps) they don't need to submit the form at all. In https://github.com/cisagov/get.gov/issues/289, we tested out the viability of updating the form with a prototype. In #300, we finalized the content updates. Now, let's implement the changes!

### Acceptance criteria

- [x] Reformat the contact form prototype with updates from the [content doc](https://docs.google.com/document/d/1kmw4HHacwl_sHyPvNmInRrFzguCaT-F60t_qX-ki7kI/edit) 
- [x] Test out prototype with existing contact form submissions (acting as the past submitter, would you have been able to find answers and/or reach out at the end using the new form?)
   - [ ] reach out to Cameron for some examples
- [ ] Test out accessibility (Microsoft Forms has accessibility issues, particularly with tabbing through multiple choice options. Accessibility issues will not be addressed in this ticket, but should take note)
- [x] Share prototype with team for final feedback
- [ ] Replace existing contact form with prototype
- [ ] See how new contact work affects helpdesk volume, address any potential issues that come up a week after implementation

### Additional context

Link to [Google doc](https://docs.google.com/document/d/1kmw4HHacwl_sHyPvNmInRrFzguCaT-F60t_qX-ki7kI/edit)
Link to [prototype](https://forms.office.com/Pages/ResponsePage.aspx?id=bOfNPG2UEkq7evydCEI1SqHke9Gh6wJEl3kQ5EjWUKlURE04OUo3WTYyUEhIVENXSFlGNU01WjVaNy4u)

### Links to other issues

Steps for updating the form: 
1. #288 
2. #289 
3. #300 
4. #303 (📍 YOU ARE HERE)

Note; This effort will update the Microsoft Form, but will not replace it. We will work on replacing the contact form with our own customized solution in [#2011](https://github.com/cisagov/manage.get.gov/issues/2011) and [#2099](https://github.com/cisagov/manage.get.gov/issues/2099)

**Comment by vickyszuchin** [comment]
Per design/product meeting, @katypies and @witha-c are the key reviewers.

**Comment by vickyszuchin** [comment]
Per guideline, all "In review" tickets from Sprint 50 will moved forward at noon EST on Day 4 to current sprint (Sprint 51).
