### ISSUE TITLE
Content: Update content on get.gov to when User profile feature is released 

### ISSUE THREAD

**Issue by gabydisarli** [cisagov/get.gov#305]
### Issue description

As part of the new [User profile feature](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?m=auto&node-id=3991-6551&focus-id=9-6826) ([also](https://www.figma.com/design/xFtGLHVrhp0lvwh0gYWnbx/.gov-Designs-CISA?m=auto&node-id=47-62844&focus-id=2402-7440)), we'll need to update any language across get.gov which refers to the "Your contact information" either in the domain request form or domain management pages since this information now lives on the profile page. Examples of this language appear on get.gov/domains/before and https://get.gov/help/account-management/#update-your-contact-information-email-phone

### Acceptance criteria

- [x] Identify all places where content needs to be updated. (see cisagov/manage.get.gov#2360)
- [x] Make content updates on Google Doc ([WIP content](https://docs.google.com/document/d/1JluHpbVe7ky02-TFsR_eA_wRVFkZrDst4eL_XV4d33A/edit))
- [x] Share for team approval

### Additional context

Note that this work can't be merged/released until the User profile is released.

### Links to other issues

🔄  [User profile feature slice](https://github.com/orgs/cisagov/projects/26/views/52)
Dev ticket to link to this new content in registrar: #[2360](https://github.com/cisagov/manage.get.gov/issues/2360)

**Comment by h-m-f-t** [comment]
@Katherine-Osos, can you review the [WIP content](https://docs.google.com/document/d/1JluHpbVe7ky02-TFsR_eA_wRVFkZrDst4eL_XV4d33A/edit?usp=sharing)?

**Comment by vickyszuchin** [comment]
Per guideline, all "In review" tickets from Sprint 48 will moved forward at noon EST on Day 4 of new sprint (Sprint 49).

**Comment by Katherine-Osos** [comment]
@h-m-f-t I reviewed the content and suggested some edits. Also had a few questions that I inserted within the comments.

**Comment by h-m-f-t** [comment]
@Katherine-Osos I accepted most changes and rejected one or two; see your email? Also made a couple very small changes.
