### ISSUE TITLE
Update /about/product with meaningful, user-facing changes since January '24

### ISSUE THREAD

**Issue by PaulKuykendall** [cisagov/get.gov#318]
### Issue description

We want to update [/about/product/](https://get.gov/about/product/) with changes we've made since the January 2024 launch of the registrar.

### Acceptance criteria

- [x] Review [system release notes](https://github.com/cisagov/manage.get.gov/releases) to identify the features we want to write about (and when they landed in production)
- [x] Draft content updates with a real "release notes" vibe [Working Copy](https://docs.google.com/document/d/12ujTYh4F1Wmm64WF0zwHO_oqMCLkOHJajrzaO8qzhLQ/edit#heading=h.ir437yjevvic)
- [x] Review content updates with dev and design
- [ ] Convert content to Markdown and add to https://github.com/cisagov/get.gov/blob/main/pages/about/product_updates.md
- [ ] Have a discussion in Product Team Huddle about maintaining this going forward. Also discuss whether we'll create a design/dev issue for the note in "Additional context' below

### Additional context

* We should consider adding a "What's new" button or link in the registrar, linking to this section of the website. Like GitHub Projects does:
<img width="198" alt="image" src="https://github.com/user-attachments/assets/37cf0749-3c70-49e9-8ac0-11e56c5ee6ae">

**Comment by h-m-f-t** [comment]
I've updated the issue and think it's ready to be Ready.

**Comment by vickyszuchin** [comment]
Any "In progress" tickets from Sprint 55 will be moved to the current sprint (Sprint 56) at noon EST (10am MT/9am PST) on Day 1.

**Comment by katypies** [comment]
@h-m-f-t is going to add this change to the /about page to include in a pending PR on get.gov.

There are a few other things we may want to retroactively add but will spin out new tickets to handle that.
