### ISSUE TITLE
Update dependabot setup to update main not beta

### ISSUE THREAD

**Issue by abroddrick** [cisagov/get.gov#319]
### Issue description

Our current dependabot setup was creating dependabot's for the beta branch not the main branch. Beta was used for beta.get.gov before we went live, while main is what we current use for production get.gov code. 

### Acceptance criteria

- [ ] dependabot now updates main

**Comment by CocoByte** [comment]
Inspection revealed that dependabot had already switched over to main after the beta PRs were closed.  Work for this ticket was switched over to clearing the new PRs for main that dependabot had made.  All open dependabot PRs have been reviewed and either closed or merged.
